### ISSUE TITLE
Button component won't accept named icon (string) as attribute

### ISSUE THREAD

**Issue by wwqrd** [codaco/Network-Canvas-UI#52]
This line seems to indicate that we can use Icon names rather than needing to pass a component:
https://github.com/codaco/Network-Canvas-UI/blob/master/src/components/Button.js#L13

But it looks like that code might be broken:
<img width="1028" alt="screen shot 2018-04-30 at 15 06 59" src="https://user-images.githubusercontent.com/776599/39431428-9692d2f4-4c88-11e8-9e50-d9592f4e02d4.png">

**Comment by bryfox** [comment]
As far as I can tell, this was only an error when trying to reference a non-existent icon.

That error was fixed as of https://github.com/codaco/Network-Canvas-UI/commit/a3fc921623cd5cef9afd097a3c5e5f4916f3547e. Current behavior is to not display a missing icon. We could log a warning for clarity (by merging #75), but otherwise this appears to be fixed.
