### ISSUE TITLE
Include basic scroll components

### ISSUE THREAD

**Issue by bryfox** [codaco/Network-Canvas-UI#55]
Edit: See comments below; UI should have a basic scroller; existing scroll functionality is intended mostly for Node Lists, which can stay in NC for now.

I'd like to make use of NC's scrolling functionality in Server:

- Scroller component
- scrolling behavior
- ...and related styles

This would be pretty straightforward, but (as is) would add some dependencies here: prop-types and lodash.

If that sounds OK, I can open PRs with the changes.

**Comment by jthrilly** [comment]
Would this be for a node container? If not, it might be a good idea to have a more generic scrollable container in UI that is more suitable for desktop, and then have the additional styling and functionality needed for a scrollable node list in NC.

The reason I say this is that the scroller really was developed specifically to give visual affordances for a scrollable node list, rather than say having the affordances of a scrollable item list from the windows or macOS SDKs.

**Comment by bryfox** [comment]
I see. No, it's not needed for node lists; I'd assumed it would be used for any scrollable area.

Would a generic scroller provide anything other than `overflow: auto`? If not, a component is probably overkill for any needs I'm imagining (vs. the CSS one-liner).

**Comment by jthrilly** [comment]
Well, depending on how "smart" you needed it to be, it could also deal with styling the scrollbars in a network canvas type way, and perhaps support something like a 'scollTo' prop? There's also some CSS you could do to make it feel more native (rebound scrolling?). I'm not sure what your use case is in Server.

**Comment by bryfox** [comment]
I don't think I need any special behavior, just content overflow. Some use cases: sidebar with excess nav items; dashboard view contents; panels within dashboard containing scrolled content (e.g., device list). In Network Canvas, I'll need to scroll the area displaying protocols from a Server.

My inclination would be to unify scrolling behavior everywhere (except node lists?). `overflow:auto` meets my needs, but you mentioned Network Canvas styling scrollbars, which sounds like something that could be shared. However, I don't see where that's happening. I do see the node list `scrolling`/`Scroller` used for card lists & the stages menu, which might not be desired (based on your comments above)?

**Comment by jthrilly** [comment]
> I do see the node list scrolling/Scroller used for card lists & the stages menu, which might not be desired (based on your comments above)?

Yeah the reuse in those contexts is somewhat marginal - the card list is definitely appropriate since it has the same affordances, but the menu probably isn't. This will of course be removed when the menu is redone.

> I don't think I need any special behavior, just content overflow. Some use cases: sidebar with excess nav items; dashboard view contents; panels within dashboard containing scrolled content (e.g., device list). In Network Canvas, I'll need to scroll the area displaying protocols from a Server.

Based on what you've said I think perhaps a scrollable mixin, along with a desktop scrollable component -- both implemented within UI -- would be appropriate. The mixin can implement `overflow-` and `-webkit-overflow-scrolling`, and can be used by the existing scrollable component styles, which will then add its NC specific decorations on top. Meanwhile the new desktop scrollable component can implement native platform feeling css. What do you think?

We do have a couple of planned instances of horizontal scrolling, which should be taken into account (perhaps two mixins to account for the direction of scrolling?).

**Comment by bryfox** [comment]
I initially opened this, but I no longer think there's any benefit to reusing scrolling. The NC component/behavior deals with a mask-image and -webkit-overflow-scrolling, neither of which are of use to Server (or Architect, from what I've seen). All we're really left with is `overflow[-xy]: auto`, which is easier to just work with directly.

I'm closing this; if others disagree, please re-open.
